version: "3.3"
services:
  kafka_nginx:
    image: nginx-kafka:1.0.55
    restart: unless-stopped
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/.samplepwd:/etc/nginx/.samplepwd
      - ./data/scripts/:/usr/share/nginx/html
    ports:
    - "80:80"
    - "443:443"
    - "8080:8080"
    networks:
      external:
        ipv4_address: 172.16.238.2
  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:0.9.0
    restart: unless-stopped
    ports:
    - "9113:9113"
    command:
    - -nginx.scrape-uri
    - http://kafka_nginx:8080/stub_status
    depends_on:
    - kafka_nginx
    networks:
      external:
        ipv4_address: 172.16.238.3

networks:
  external:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
        driver: default
        config:
          - subnet: 172.16.238.0/24
            gateway: 172.16.238.1
